name: zd_age_fans
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3 #加密
  flutter_riverpod: ^2.4.9 #状态管理
  cached_network_image: ^3.3.1 #加载网络图片
  dio: ^5.4.3+1 #网络
  pull_to_refresh: ^2.0.0 #刷新
  easy_refresh: ^3.3.4 #刷新
  carousel_slider: ^4.2.1 #轮播
  sliding_up_panel: ^2.0.0+1 #滑动吸顶
  #fluttertoast: ^8.2.2 #透明弹出框
  bot_toast: ^4.1.3 #loading or toast
  # better_player: ^0.0.83 #播放器
  video_player: ^2.9.1
  chewie: ^1.8.1 #播放器
  curved_navigation_bar: ^1.0.6 #tab bar
  # rinf: #rust_in_flutter
  protobuf: ^3.1.0
  flutter_rust_bridge: ^2.1.0
  quiver: ^3.2.1 #工具库
  # json转model
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  # json5_model: ^2.0.1
  # 他人推荐
  # retrofit: ^4.0.1
  # auto_route: ^7.8.3
  # rxdart: ^0.28.0
  # window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 #启动图标
  # json转model
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter_launcher_icons:
  image_path: "assets/icons/icon_512.png"
  remove_alpha_ios: true
  ios: true
  # image_path_ios: "assets/icons/icon_512.png"
  # image_path_android: "assets/icons/icon_512.png"
  android: true
  macos:
    generate: true
    #image_path: "assets/icons/macos/"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/icon_512.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
